require: rubocop-rspec
inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml
AllCops:
  Exclude:
    - gemfiles/**/*
    - tmp/**/*
    - vendor/**/*
GitHub/RailsControllerRenderLiteral:
  Enabled: false
GitHub/RailsControllerRenderPathsExist:
  Enabled: false
