// flow-typed signature: 805295ca62a80e1e487e41973174004f
// flow-typed version: <<STUB>>/react-apollo_v2.1.11/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-apollo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-apollo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-apollo/ApolloConsumer' {
  declare module.exports: any;
}

declare module 'react-apollo/ApolloProvider' {
  declare module.exports: any;
}

declare module 'react-apollo/browser' {
  declare module.exports: any;
}

declare module 'react-apollo/getDataFromTree' {
  declare module.exports: any;
}

declare module 'react-apollo/graphql' {
  declare module.exports: any;
}

declare module 'react-apollo/hoc-utils' {
  declare module.exports: any;
}

declare module 'react-apollo/mutation-hoc' {
  declare module.exports: any;
}

declare module 'react-apollo/Mutation' {
  declare module.exports: any;
}

declare module 'react-apollo/parser' {
  declare module.exports: any;
}

declare module 'react-apollo/query-hoc' {
  declare module.exports: any;
}

declare module 'react-apollo/Query' {
  declare module.exports: any;
}

declare module 'react-apollo/queryRecycler' {
  declare module.exports: any;
}

declare module 'react-apollo/react-apollo.browser.umd' {
  declare module.exports: any;
}

declare module 'react-apollo/react-apollo.umd' {
  declare module.exports: any;
}

declare module 'react-apollo/renderToStringWithData' {
  declare module.exports: any;
}

declare module 'react-apollo/subscription-hoc' {
  declare module.exports: any;
}

declare module 'react-apollo/Subscriptions' {
  declare module.exports: any;
}

declare module 'react-apollo/test-links' {
  declare module.exports: any;
}

declare module 'react-apollo/test-utils' {
  declare module.exports: any;
}

declare module 'react-apollo/types' {
  declare module.exports: any;
}

declare module 'react-apollo/withApollo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-apollo/ApolloConsumer.js' {
  declare module.exports: $Exports<'react-apollo/ApolloConsumer'>;
}
declare module 'react-apollo/ApolloProvider.js' {
  declare module.exports: $Exports<'react-apollo/ApolloProvider'>;
}
declare module 'react-apollo/browser.js' {
  declare module.exports: $Exports<'react-apollo/browser'>;
}
declare module 'react-apollo/getDataFromTree.js' {
  declare module.exports: $Exports<'react-apollo/getDataFromTree'>;
}
declare module 'react-apollo/graphql.js' {
  declare module.exports: $Exports<'react-apollo/graphql'>;
}
declare module 'react-apollo/hoc-utils.js' {
  declare module.exports: $Exports<'react-apollo/hoc-utils'>;
}
declare module 'react-apollo/index' {
  declare module.exports: $Exports<'react-apollo'>;
}
declare module 'react-apollo/index.js' {
  declare module.exports: $Exports<'react-apollo'>;
}
declare module 'react-apollo/mutation-hoc.js' {
  declare module.exports: $Exports<'react-apollo/mutation-hoc'>;
}
declare module 'react-apollo/Mutation.js' {
  declare module.exports: $Exports<'react-apollo/Mutation'>;
}
declare module 'react-apollo/parser.js' {
  declare module.exports: $Exports<'react-apollo/parser'>;
}
declare module 'react-apollo/query-hoc.js' {
  declare module.exports: $Exports<'react-apollo/query-hoc'>;
}
declare module 'react-apollo/Query.js' {
  declare module.exports: $Exports<'react-apollo/Query'>;
}
declare module 'react-apollo/queryRecycler.js' {
  declare module.exports: $Exports<'react-apollo/queryRecycler'>;
}
declare module 'react-apollo/react-apollo.browser.umd.js' {
  declare module.exports: $Exports<'react-apollo/react-apollo.browser.umd'>;
}
declare module 'react-apollo/react-apollo.umd.js' {
  declare module.exports: $Exports<'react-apollo/react-apollo.umd'>;
}
declare module 'react-apollo/renderToStringWithData.js' {
  declare module.exports: $Exports<'react-apollo/renderToStringWithData'>;
}
declare module 'react-apollo/subscription-hoc.js' {
  declare module.exports: $Exports<'react-apollo/subscription-hoc'>;
}
declare module 'react-apollo/Subscriptions.js' {
  declare module.exports: $Exports<'react-apollo/Subscriptions'>;
}
declare module 'react-apollo/test-links.js' {
  declare module.exports: $Exports<'react-apollo/test-links'>;
}
declare module 'react-apollo/test-utils.js' {
  declare module.exports: $Exports<'react-apollo/test-utils'>;
}
declare module 'react-apollo/types.js' {
  declare module.exports: $Exports<'react-apollo/types'>;
}
declare module 'react-apollo/withApollo.js' {
  declare module.exports: $Exports<'react-apollo/withApollo'>;
}
